project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "devise_customed/registrations"}
  resources :users
  root 'products#index'
  resources :favorites
  resources :transaction_items
  resources :transaction_orders
  resources :cartitems
  resources :sizes
  get 'products/remove_picture', to: 'products#remove_picture'
  resources :products
  get 'all', to: "products#inspect", as: "inspect_all"
  resources :colors
  resources :product_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'admin', to: 'admin#show'
  get 'test', to: 'admin#test'
  get 'transaction_orders/:id/adminedit', to: 'transaction_orders#adminedit', as: "admin_edit_transaction_orders"
  get 'transaction_orders/:id/receive_product', to: 'transaction_orders#receive_product', as: "receive_product"
  match 'favorites/remove', to: 'favorites#destroy', as: "remove_product_favorites", via: :post
  match 'favorites/reverse', to: 'favorites#reverse', via: :post
  match 'users/:id/change_password', to: 'users#change_password', via: :post, as: "change_password"
  match 'api/getmoney',to:"transaction_orders#setpaid", via: :get, as:"receive_money"
end

project/app/models/transaction_order.rb
class TransactionOrder < ApplicationRecord
  has_many :order_products
  has_many :products,through: :order_products
  belongs_to :user
  validates :address,:name,:phone,:postcode,presence: true

end

project/app/controllers/transaction_orders_controller.rb
class TransactionOrdersController < ApplicationController
  include ApplicationHelper
  before_action :set_transaction_order, only: [:show, :edit, :update, :destroy, :adminedit,:receive_product]
  before_action :useriscustomer, only: [:new,:edit,:create,:receive_product]
  before_action :userisadmin, only: [:index, :adminedit]
  before_action :usersignedin,only: [:update,:destroy]
  skip_before_action :verify_authenticity_token, only: [:create]

  # GET /transaction_orders
  # GET /transaction_orders.json
  def index
    @transaction_orders = TransactionOrder.all
  end

  def setpaid
    @transaction_order=TransactionOrder.find(params[:id])
    if @transaction_order.sstatus==0
      @transaction_order.sstatus=1
      @transaction_order.save
    end
    redirect_to @transaction_order
  end


  # GET /transaction_orders/1
  # GET /transaction_orders/1.json
  def show
  end

  # GET /transaction_orders/new
  def new
    @transaction_order = TransactionOrder.new
    @transaction_order.user = current_user
    @transaction_order.sum = 0
    @targetproducts = Array.new
    current_user.cartitems.each do |x|
      @targetproducts << x.product
      @transaction_order.sum += x.product.price * x.quantity
    end
    if @targetproducts.size == 0
      redirect_to root_path, notice: "购物车为空，接着逛逛吧"
    end

    #targetproducts用于预览客户即将要结账的所有商品


  end

  # GET /transaction_orders/1/edit
  def edit
    unless @transaction_order.sstatus == 0
      redirect_to @transaction_order, notice: "该订单不能修改"
    end
  end

  def adminedit
    @bought = Product.left_joins(:order_products).select("products.id as product_final_id, *").where('transaction_order_id=' + @transaction_order.id.to_s)

  end

  # POST /transaction_orders
  # POST /transaction_orders.json
  def create
    @transaction_order = TransactionOrder.new(transaction_order_params) #name,address,phone,postcode
    @transaction_order.user = current_user #用户
    @transaction_order.sum = 0
    @targetproducts = Array.new
    current_user.cartitems.each do |x|
      @targetproducts << x
      @transaction_order.sum += x.product.price * x.quantity
    end
    #并且计算总额
    respond_to do |format|
      if @transaction_order.save
        #清空当前用户的购物车
        @targetproducts.each do |x|
          #为订单和产品之间添加关系
          @newrelation = OrderProduct.new
          @newrelation.transaction_order = @transaction_order
          @newrelation.product = x.product
          @newrelation.quantity = x.quantity
          @newrelation.save
        end
        Cartitem.where('user_id=' + current_user.id.to_s).delete_all
        format.html { redirect_to @transaction_order, notice: '订单创建成功' }
        format.json { render :show, status: :created, location: @transaction_order }
      else
        format.html { render :new }
        format.json { render json: @transaction_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def receive_product
    if current_user!=@transaction_order.user
      redirect_to root_path, notice: "非法操作"
      return
    end
    if @transaction_order.sstatus!=2
      redirect_to root_path, notice: "非法操作"
      return
    end
    @transaction_order.sstatus=4
    respond_to do |format|
      if @transaction_order.save
        format.html { redirect_to @transaction_order, notice: 'Transaction order was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction_order }
      else
        format.html { render :edit }
        format.json { render json: @transaction_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaction_orders/1
  # PATCH/PUT /transaction_orders/1.json
  def update
    if @transaction_order.user != current_user && !current_user.isadmin?
      redirect_to root_path, notice: "非法操作"
      return
    end
    if @transaction_order.sstatus != 0 && !current_user.isadmin?
      redirect_to root_path, notice: "非法操作"
      return
    end
    if !current_user.isadmin?
      respond_to do |format|
        if @transaction_order.update(transaction_order_params)
          format.html { redirect_to @transaction_order, notice: 'Transaction order was successfully updated.' }
          format.json { render :show, status: :ok, location: @transaction_order }
        else
          format.html { render :edit }
          format.json { render json: @transaction_order.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @transaction_order.update(transaction_order_params)
          format.html { redirect_to transaction_orders_path, notice: 'Transaction order was successfully updated.' }
          format.json { render :show, status: :ok, location: @transaction_order }
        else
          format.html { render :edit }
          format.json { render json: @transaction_order.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /transaction_orders/1
  # DELETE /transaction_orders/1.json
  def destroy
    unless @transaction_order.user == current_user
      redirect_to root_path, notice: "非法操作"
      return
    end
    if @transaction_order.sstatus != 0
      redirect_to @transaction_order, notice: "该订单不能取消"
    end
    @transaction_order.sstatus = 3
    @transaction_order.save
    respond_to do |format|
      format.html { redirect_to @transaction_order, notice: "订单已经成功取消" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction_order
    @transaction_order = TransactionOrder.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_order_params
    if !current_user.nil? and current_user.isadmin? #管理员允许更改的参数！
      params.require(:transaction_order).permit(:address, :name, :phone, :postcode, :email, :note, :sstatus)
    else
      if !current_user.nil? and !current_user.isadmin?
        params.require(:transaction_order).permit(:address, :name, :phone, :postcode, :email, :note)
      end
    end
  end
end

project/app/helpers/transaction_orders_helper.rb
module TransactionOrdersHelper

  def get_paid_status transaction_order
    get_paid_status_by_id transaction_order.sstatus
  end

  def get_paid_status_by_id id
    if id == 0
      return "待付款"
    end
    if id == 1
      return "已支付"
    end
    if id == 2
      return "已发货"
    end
    if id == 3
      return "已取消"
    end
    if id == 4
      return "已完成"
    end
    if id == 5
      return "已退款"
    end
  end
end

project/app/views/transaction_orders/_form.html.erb
<p>总价格</p>
<p><%=@transaction_order.sum %>元</p>
<%= form_with(model: transaction_order, local: true) do |form| %>
  <% if transaction_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction_order.errors.count, "error") %> prohibited this transaction_order from being saved:</h2>

      <ul>
        <% transaction_order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_area :phone %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_area :postcode %>
  </div>

  <div class="field">
    <%= form.label :sstatus %>
    <%= form.text_area :sstatus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/transaction_orders/adminedit.html.erb
<%= render 'header_admin' %>

<div class="main-container">
  <div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
      <div class="page-header">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="title">
              <h4>处理订单</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "管理后台", admin_path %></li>
                <li class="breadcrumb-item"><%= link_to "所有订单", transaction_orders_path %></li>
                <li class="breadcrumb-item active" aria-current="page">处理订单</li>
              </ol>
            </nav>
          </div>
          <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                January 2018
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Export List</a>
                <a class="dropdown-item" href="#">Policies</a>
                <a class="dropdown-item" href="#">View Assets</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Default Basic Forms Start -->


      <div class="pd-20 card-box mb-30">
        <div class="clearfix">
          <div class="pull-left">
            <h4 class="text-blue h4">编辑订单</h4>
            <p class="mb-0">您可以在此查看和编辑该订单的详情。</p>
          </div>
          <div class="pull-right">
            <input form="edit_product" type='submit' class="btn btn-primary btn--large scroll-click" rel="content-y" data-toggle="collapse" role="button">
          </div>
        </div>
        <form id='edit_product' enctype="multipart/form-data" action="/transaction_orders/<%= @transaction_order.id %>" accept-charset="UTF-8" method="post">
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">订单ID</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" value="<%= @transaction_order.id %>" disabled="disabled">
            </div>
          </div>
          <input hidden="hidden" value="patch" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">订单状态</label>
            <div class="col-sm-12 col-md-10">
              <select name="transaction_order[sstatus]" class="custom-select col-12">
                <option value="<%= @transaction_order.sstatus %>" selected=""><%= get_paid_status @transaction_order %></option>
                <% for i in 0..3 %>
                  <% if i == @transaction_order.sstatus %>
                    <% next %>
                  <% end %>
                  <option value="<%= i %>"><%= get_paid_status_by_id i%></option>
                <% end %>
              </select>
            </div>
          </div>


          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">下单用户名</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" disabled="disabled" value="<%= @transaction_order.user.name %>">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">收货人姓名</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" name='transaction_order[name]' value="<%= @transaction_order.name %>">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">收货人电话</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" name='transaction_order[phone]' value="<%= @transaction_order.phone %>">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">收货人邮箱</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" name='transaction_order[email]' value="<%= @transaction_order.email %>">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">收货地址</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" name='transaction_order[address]' value="<%= @transaction_order.address %>">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">邮编</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" name='transaction_order[postcode]' value="<%= @transaction_order.postcode %>">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">订单金额（元）</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" disabled="disabled" value="<%= @transaction_order.sum %>">
            </div>
          </div>
        </form>
      </div>
      <!-- 接下来这里是 -->
      <div class="card-box mb-30">
        <h2 class="h4 pd-20">订单中的商品列表</h2>
        <table class="data-table table nowrap ">
          <thead>
          <tr>
            <th>商品</th>
            <th>商品名称</th>
            <th>单价</th>
            <th>购买件数</th>
          </tr>
          </thead>
          <tbody>
          <% @bought.each do |x| %>

            <tr>
              <td>
                <% unless x.pics.size == 0 %>
                  <img src="<%= Product.find(x.product_id).pics[0].url %>" width="70" height="70" alt="">
                <% end %>
              </td>
              <td class="table-plus">
                <h5 class="font-16"><%= x.name %></h5>
              </td>
              <td>¥<%= x.price %></td>
              <td><%= x.quantity %></td>
              <td>
                <div class="dropdown">
                  <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                    <i class="dw dw-more"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                    <a class="dropdown-item" href="<%= product_path x.product_id %>"><i class="dw dw-eye"></i> 查看商品</a>
                    <a class="dropdown-item" href="<%= edit_product_path x.product_id %>"><i class="dw dw-edit2"></i>
                      编辑商品</a>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- Input Validation End -->

  <div class="footer-wrap pd-20 mb-20 card-box">
    电子商务管理后台 2020Ruby大作业
    <a href="http://www.bootstrapmb.com/" target="_blank">By alangy</a>
  </div>


</div>
<%= render 'footer_admin' %>
</div>

project/app/views/transaction_orders/edit.html.erb
<h1>Editing Transaction Order</h1>

<%= render 'form', transaction_order: @transaction_order %>

<%= link_to 'Show', @transaction_order %> |
<%= link_to 'Back', transaction_orders_path %>

project/app/views/transaction_orders/index.html.erb
<%= render 'application/header_admin' %>

<div class="main-container">
  <div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
      <div class="page-header">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="title">
              <h4>订单管理</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "管理后台", admin_path %></li>
                <li class="breadcrumb-item active" aria-current="page">订单管理</li>
              </ol>
            </nav>
          </div>
          <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
              <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                January 2018
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Export List</a>
                <a class="dropdown-item" href="#">Policies</a>
                <a class="dropdown-item" href="#">View Assets</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Simple Datatable start -->
      <!-- Export Datatable start -->
      <div class="card-box mb-30">
        <div class="pd-20">
          <h4 class="text-blue h4">所有订单</h4>
          <p class="mb-0">您可以在此查看所有订单，发货订单，或者采用下面的工具栏导出订单（中文编码会导致乱码，很遗憾目前没有找到Linux上的解决方法）</p>
          <p class="mb-0">您只能操作发货已付款的订单。</p>
        </div>
        <div class="pb-20">
          <table class="table hover multiple-select-row data-table-export nowrap">
            <thead>
            <tr>
              <th class="table-plus datatable-nosort">订单包含的商品</th>
              <th>用户名</th>
              <th>收件人姓名</th>
              <th>收件地址</th>
              <th>邮编</th>
              <th>收件人联系电话</th>
              <th>收件人电子邮箱</th>
              <th>订单总额</th>
              <th>订单状态</th>
              <th class="datatable-nosort">操作</th>
            </tr>
            </thead>
            <tbody>
            <% @transaction_orders.each do |x| %>
              <tr>
                <td class="table-plus">
                  <%= x.products.first.name %>
                  <% if x.products.size != 1 %>
                    ...等商品
                  <% end %>
                </td>
                <td><%=x.user.name %></td>
                <td><%=x.name %></td>
                <td><%=x.address %></td>
                <td><%=x.postcode %></td>
                <td><%=x.phone %></td>
                <td><%=x.email %></td>
                <td><%=x.sum %>元</td>
                <td><%=get_paid_status x %></td>
                <td>
                  <div class="dropdown">
                    <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                      <i class="dw dw-more"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                      <a class="dropdown-item" href="#"><i class="dw dw-eye"></i>快速标记为已发货</a>
                      <a  href="<%=admin_edit_transaction_orders_path x %>" class="dropdown-item"><i class="dw dw-edit2"></i>处理订单</a>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- Export Datatable End -->
    <div class="footer-wrap pd-20 mb-20 card-box">
      电子商务管理后台 2020Ruby大作业
      <a href="email://alangy@buaa.edu.cn" target="_blank">By alangy</a>
    </div>
  </div>


  <%= render 'footer_admin' %>
</div>

project/app/views/transaction_orders/show.html.erb
<%=render 'header' %>
<!-- ::::::  Start  Breadcrumb Section  ::::::  -->
<div class="page-breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <ul class="page-breadcrumb__menu">
          <li class="page-breadcrumb__nav"><a href="#">主页</a></li>
          <li class="page-breadcrumb__nav active">查看订单</li>
        </ul>
      </div>
    </div>
  </div>
</div> <!-- ::::::  End  Breadcrumb Section  ::::::  -->

<!-- ::::::  Start  Main Container Section  ::::::  -->
<main id="main-container" class="main-container">
  <div class="container">
    <div class="row">
      <!-- Start Client Shipping Address -->
      <div class="col-lg-7">
        <div class="section-content">
          <h5 class="section-content__title">收货人信息</h5>
        </div>
        <form action="#" method="post" class="form-box">
          <div class="row">
            <div class="col-md-6">
              <div class="form-box__single-group">
                <label for="form-name">收货人姓名</label>
                <input type="text" id="form-name" value="<%= @transaction_order.name %>" disabled="disabled">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-box__single-group">
                <label for="form-postcode">邮编</label>
                <input type="text" id="form-postcode" value="<%= @transaction_order.postcode %>" disabled="disabled">
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-box__single-group">
                <label for="form-address">收货地址</label>
                <input type="text" id="form-address" value="<%= @transaction_order.address %>" disabled="disabled">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-box__single-group">
                <label for="form-phone">收货人电话</label>
                <input type="text" id="form-phone" value="<%= @transaction_order.phone %>" disabled="disabled">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-box__single-group">
                <label for="form-email">收货人电子邮箱</label>
                <input type="email" id="form-email" value="<%= @transaction_order.email %>" disabled="disabled">
              </div>
            </div>

            <div class="col-md-12">
              <div class="form-box__single-group">
                <h6>附加信息</h6>
                <label for="form-additional-info">订单备注</label>
                <textarea id="form-additional-info" rows="5" value="<%= @transaction_order.note %> " disabled="disabled"></textarea>
              </div>
            </div>
            <!-- Add Another Shipping Address -->
          </div>
        </form>
      </div> <!-- End Client Shipping Address -->

      <!-- Start Order Wrapper -->
      <div class="col-lg-5">
        <div class="your-order-section">
          <div class="section-content">
            <h5 class="section-content__title">订单详情</h5>
          </div>
          <div class="your-order-box gray-bg m-t-40 m-b-30">
            <div class="your-order-product-info">
              <div class="your-order-top d-flex justify-content-between">
                <h6 class="your-order-top-left font--bold">商品</h6>
                <h6 class="your-order-top-right font--bold">价格</h6>
              </div>
              <ul class="your-order-middle">
                <% @totalcost = 0.0 %>
                <% @transaction_order.order_products.includes(:product).each do |item| %>
                  <li class="d-flex justify-content-between">
                    <span class="your-order-middle-left font--semi-bold"><%= item.product.name %>
                      X <%= item.quantity %></span>
                    <span class="your-order-middle-right font--semi-bold">¥<%= item.quantity * item.product.price %></span>
                    <% @totalcost += item.quantity * item.product.price %>
                  </li>
                <% end %>
              </ul>
              <div class="your-order-bottom d-flex justify-content-between">
                <h6 class="your-order-bottom-left font--bold">运费</h6>
                <span class="your-order-bottom-right font--semi-bold">全场免邮</span>
              </div>
              <div class="your-order-buttom d-flex justify-content-between">
                <h5 class="your-order-total-left font--bold">总价</h5>
                <h5 class="your-order-total-right font--bold">¥<%= @totalcost %></h5>

              </div>
              <div class="your-order-middle d-flex justify-content-between">
                <h5 class="your-order-total-left font--bold">订单状态</h5>
                <h5 class="your-order-total-right font--bold"><%= get_paid_status @transaction_order %></h5>
              </div>


              <% if @transaction_order.sstatus == 0 %>

                <div class="payment-method">
                  <div class="payment-accordion element-mrg">
                    <div class="panel-group" id="accordion">
                      <div class="panel payment-accordion">
                        <div class="panel-heading" id="method-one">
                          <h4 class="panel-title">
                            <a class="collapsed d-flex justify-content-between align-items-center" href="http://www.alipay.com">
                              点击使用支付宝支付（未接入）
                            </a>
                          </h4>
                        </div>
                      </div>
                      <div class="panel payment-accordion">
                        <div class="panel-heading" id="method-two">
                          <h4 class="panel-title">
                            <a class="collapsed d-flex justify-content-between align-items-center" href="https://tencent.com">
                              点击使用微信支付（未接入）
                            </a>
                          </h4>
                        </div>
                      </div>
                      <div class="panel payment-accordion">
                        <div class="panel-heading" id="method-three">
                          <h4 class="panel-title">
                            <a class="collapsed d-flex justify-content-between align-items-center" href="#method3">
                              点击选择到付
                            </a>
                          </h4>
                        </div>
                      </div>
                      <div class="panel payment-accordion">
                        <div class="panel-heading" id="method-two">
                          <h4 class="panel-title">
                            <a class="collapsed d-flex justify-content-between align-items-center" href="<%=receive_money_path%>?id=<%=@transaction_order.id %>">
                              点此假装进行了付款
                            </a>
                          </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <% if @transaction_order.sstatus == 0 %>
            <%= link_to "取消订单", @transaction_order, method: :delete, class: "btn btn--block btn--small btn--radius btn--red btn--red-hover-black btn--uppercase font--bold" %>
          <% end %>
          <% if @transaction_order.sstatus == 2 %>
            <%= link_to "确认收货", receive_product_url(@transaction_order), class: "btn btn--block btn--small btn--radius btn--red btn--red-hover-black btn--uppercase font--bold" %>
          <% end %>
        </div>
      </div> <!-- End Order Wrapper -->
    </div>
  </div>
</main> <!-- ::::::  End  Main Container Section  ::::::  -->

<%= render 'footer' %>