project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "devise_customed/registrations"}
  resources :users
  root 'products#index'
  resources :favorites
  resources :transaction_items
  resources :transaction_orders
  resources :cartitems
  resources :sizes
  get 'products/remove_picture', to: 'products#remove_picture'
  resources :products
  get 'all', to: "products#inspect", as: "inspect_all"
  resources :colors
  resources :product_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'admin', to: 'admin#show'
  get 'test', to: 'admin#test'
  get 'transaction_orders/:id/adminedit', to: 'transaction_orders#adminedit', as: "admin_edit_transaction_orders"
  get 'transaction_orders/:id/receive_product', to: 'transaction_orders#receive_product', as: "receive_product"
  match 'favorites/remove', to: 'favorites#destroy', as: "remove_product_favorites", via: :post
  match 'favorites/reverse', to: 'favorites#reverse', via: :post
  match 'users/:id/change_password', to: 'users#change_password', via: :post, as: "change_password"
  match 'api/getmoney',to:"transaction_orders#setpaid", via: :get, as:"receive_money"
end

project/app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]
  before_action :userisadmin,only: [:index,:new,:edit,:destroy,:create,:update]


  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
    #Todo:还没有做！这里只是测试使用!
    @products=@product_type.products
    @name=@product_type.product_type_name
    @count=@product_type.products.size
    @product_types=ProductType.all


  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_type_params
      params.require(:product_type).permit(:product_type_name)
    end
end

project/app/helpers/product_types_helper.rb
module ProductTypesHelper
end

project/app/views/product_types/_form.html.erb
<%= form_with(model: product_type, local: true) do |form| %>
  <% if product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
        <% product_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_type_name %>
    <%= form.text_area :product_type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/product_types/edit.html.erb
<%= render 'header_admin' %>

<div class="main-container">
  <div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
      <div class="page-header">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="title">
              <h4>编辑商品分类</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "管理后台", admin_path %></li>
                <li class="breadcrumb-item"><%= link_to "商品分类管理", product_type_path %></li>
                <li class="breadcrumb-item active" aria-current="page">编辑商品分类</li>
              </ol>
            </nav>
          </div>
          <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                January 2018
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Export List</a>
                <a class="dropdown-item" href="#">Policies</a>
                <a class="dropdown-item" href="#">View Assets</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Default Basic Forms Start -->


      <div class="pd-20 card-box mb-30">
        <div class="clearfix">
          <div class="pull-left">
            <h4 class="text-blue h4">编辑商品分类</h4>
          </div>
          <div class="pull-right">
            <input form="edit_product" type='submit' class="btn btn-primary btn--large scroll-click" rel="content-y" data-toggle="collapse" role="button">
          </div>
        </div>
        <form id='edit_product' enctype="multipart/form-data" action="/product_types/<%= @product_type.id %>" accept-charset="UTF-8" method="post">
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">商品分类ID</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" value="<%= @product_type.id %>" disabled="disabled">
            </div>
          </div>
          <input hidden="hidden" value="patch" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">商品分类名称</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" name='product_type[product_type_name]' value="<%= @product_type.product_type_name %>">
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- Input Validation End -->

    <div class="footer-wrap pd-20 mb-20 card-box">
      电子商务管理后台 2020Ruby大作业
      <a href="http://www.bootstrapmb.com/" target="_blank">By alangy</a>
    </div>


  </div>
  <%= render 'footer_admin' %>
</div>

project/app/views/product_types/index.html.erb
<%= render 'application/header_admin' %>
<div class="main-container">
  <div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
      <div class="page-header">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="title">
              <h4>商品分类管理</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<%=admin_path %>">管理后台</a></li>
                <li class="breadcrumb-item active" aria-current="page">商品分类管理</li>
              </ol>
            </nav>
          </div>
          <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
              <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                January 2018
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Export List</a>
                <a class="dropdown-item" href="#">Policies</a>
                <a class="dropdown-item" href="#">View Assets</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Simple Datatable start -->
      <div class="card-box mb-30">
        <div class="pd-20">
          <h4 class="text-blue h4">所有分类</h4>
          <a class="btn btn-primary" href="<%=new_product_type_path %>" role="button">
            新增分类
          </a>
        </div>
        <div class="pb-20">
          <table class="data-table table stripe hover nowrap">
            <thead>
            <tr>
              <th class="table-plus datatable-nosort">分类名称</th>
              <th class="datatable-nosort">操作</th>
            </tr>
            </thead>
            <tbody>
            <% @product_types.each do |x| %>
              <tr>
                <td class="table-plus"><%= x.product_type_name %></td>
                <td>
                  <div class="dropdown">
                    <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                      <i class="dw dw-more"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                      <a  href="<%=edit_product_type_path x %>" class="dropdown-item"><i class="dw dw-edit2"></i>编辑商品分类</a>
                      <%= link_to raw("<i class=\"dw dw-delete-3\"></i> 删除商品分类</a>"), (x), :method => :delete, class: "dropdown-item" %>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="footer-wrap pd-20 mb-20 card-box">
      电子商务管理后台 2020Ruby大作业
      <a href="email://alangy@buaa.edu.cn" target="_blank">By alangy</a>
    </div>
  </div>
</div>
<%=render 'footer_admin' %>
<!-- js -->

project/app/views/product_types/new.html.erb
<%= render 'header_admin' %>

<div class="main-container">
  <div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
      <div class="page-header">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="title">
              <h4>新增商品分类</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "管理后台", admin_path %></li>
                <li class="breadcrumb-item"><%= link_to "商品分类管理", product_types_path %></li>
                <li class="breadcrumb-item active" aria-current="page">新增商品分类</li>
              </ol>
            </nav>
          </div>
          <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                January 2018
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Export List</a>
                <a class="dropdown-item" href="#">Policies</a>
                <a class="dropdown-item" href="#">View Assets</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Default Basic Forms Start -->


      <div class="pd-20 card-box mb-30">
        <div class="clearfix">
          <div class="pull-left">
            <h4 class="text-blue h4">新增商品分类</h4>
          </div>
          <div class="pull-right">
            <input form="edit_product" type='submit' class="btn btn-primary btn--large scroll-click" rel="content-y" data-toggle="collapse" role="button">
          </div>
        </div>
        <form id='edit_product' enctype="multipart/form-data" action="/product_types" accept-charset="UTF-8" method="post">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group row">
            <label class="col-sm-12 col-md-2 col-form-label">商品分类名称</label>
            <div class="col-sm-12 col-md-10">
              <input class="form-control" type="text" name='product_type[product_type_name]' >
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- Input Validation End -->

    <div class="footer-wrap pd-20 mb-20 card-box">
      电子商务管理后台 2020Ruby大作业
      <a href="http://www.bootstrapmb.com/" target="_blank">By alangy</a>
    </div>


  </div>
  <%= render 'footer_admin' %>
</div>

project/app/views/product_types/show.html.erb
<%=render 'application/show_product' %>