project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "devise_customed/registrations"}
  resources :users
  root 'products#index'
  resources :favorites
  resources :transaction_items
  resources :transaction_orders
  resources :cartitems
  resources :sizes
  get 'products/remove_picture', to: 'products#remove_picture'
  resources :products
  get 'all', to: "products#inspect", as: "inspect_all"
  resources :colors
  resources :product_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'admin', to: 'admin#show'
  get 'test', to: 'admin#test'
  get 'transaction_orders/:id/adminedit', to: 'transaction_orders#adminedit', as: "admin_edit_transaction_orders"
  get 'transaction_orders/:id/receive_product', to: 'transaction_orders#receive_product', as: "receive_product"
  match 'favorites/remove', to: 'favorites#destroy', as: "remove_product_favorites", via: :post
  match 'favorites/reverse', to: 'favorites#reverse', via: :post
  match 'users/:id/change_password', to: 'users#change_password', via: :post, as: "change_password"
  match 'api/getmoney',to:"transaction_orders#setpaid", via: :get, as:"receive_money"
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper


end

project/app/helpers/application_helper.rb
module ApplicationHelper
  def userisadmin
    unless user_signed_in?
      redirect_to new_user_session_path
      return
    end
    unless current_user.isadmin
      flash[:alert]="没有权限进行此操作"
      redirect_to root_path
    end
  end

  def useriscustomer
    unless user_signed_in?
      redirect_to new_user_session_path
      return
    end
    if current_user.isadmin
      flash[:alert]="管理员不能执行此操作"
      redirect_to root_path
    end
  end

  def usersignedin
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def isadmin?
    if user_signed_in? && current_user.isadmin
      return true
    end
    false
  end

  def iscustomer?
    if (user_signed_in?) && !(current_user.isadmin)
      return true
    end
    return false
  end

end

project/app/views/application/_footer.html.erb
<!-- Start Modal Add cart -->
<div class="modal fade" id="modalAddCart" tabindex="-1" role="dialog"
     <% if session[:registered] == true %>

     aria-hidden="false"
     <% else %>
     aria-hidden="true"
     <% end %>
     >
  <div class="modal-dialog  modal-dialog-centered modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center" id='add_cart_status'>正在添加到购物车，请稍等</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <div id='shopping_list_quickview' class="col-md-6">


            </div>
            <div class="col-md-6 modal__border">
              <span id='number' class="modal__product-cart-item">正在添加购物车，请稍等...</span>
              <ul class="modal__product-shipping-info m-tb-15">
                <li>商品价格：<span id='price'>¥</span></li>
                <li>邮费：<span id='shipping'>¥0.00</span></li>
                <li>总价：<span id='total'>¥</span></li>
              </ul>

              <div class="modal__product-cart-buttons">
                <a href="#" class="btn btn--box btn--radius btn--small btn--black btn--black-hover-red btn--uppercase btn--weight" data-dismiss="modal">继续购物</a>
                <%= link_to '查看详情并结账', cartitems_path, class: "btn btn--box btn--radius btn--small btn--black btn--black-hover-red btn--uppercase btn--weight" %>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- End Modal Add cart -->

<footer class="footer m-t-100">
  <div class="container">
    <!-- Start Footer Top Section -->
    <div class="footer__top">
      <div class="row">
        <div class="col-lg-2 col-sm-6 col-12">
          <!-- Start Footer Nav -->
          <div class="footer__menu">
            <h4 class="footer__nav-title footer__nav-title--dash footer__nav-title--dash-red">关于我们</h4>
            <ul class="footer__nav">
              <li class="footer__list"><a href="" class="footer__link">快递信息</a></li>
              <li class="footer__list"><a href="#" class="footer__link">隐私政策</a></li>
              <li class="footer__list"><a href="" class="footer__link">用户条款</a></li>
              <li class="footer__list"><a href="#" class="footer__link">联系方式</a></li>
              <li class="footer__list"><a href="" class="footer__link">退款流程</a></li>
            </ul>
          </div> <!-- End Footer Nav -->
        </div>
        <div class="col-lg-2 col-sm-6 col-12">
          <div class="footer__menu">
            <h4 class="footer__nav-title footer__nav-title--dash footer__nav-title--dash-red">我的账户</h4>
            <ul class="footer__nav">
              <% if current_user.nil? %>
                <li class="footer__list"><a href="<%= new_user_session_path %>" class="footer__link">我的账户</a></li>
                <li class="footer__list"><a href="<%= new_user_session_path %>" class="footer__link">订单</a></li>
              <% else %>
                <li class="footer__list"><a href="<%= user_path current_user %>" class="footer__link">我的账户</a></li>
                <li class="footer__list"><a href="<%= user_path current_user %>" class="footer__link">订单</a></li>

              <% end %>

              <li class="footer__list"><a href="<%= favorites_path %>" class="footer__link">我收藏的商品</a></li>
              <li class="footer__list"><a href="<%= cartitems_path %>" class="footer__link">我的购物车</a></li>
              <li class="footer__list"><a href="#" class="footer__link">常见问题</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-12">
          <div class="footer__about">
            <div class="footer__logo">
              <a href="index.html" class="footer__logo-link">
                <img src="/assets/img/logo/logo-color-red.png" alt="" class="footer__logo-img">
              </a>
            </div>
            <ul class="footer__address">
              <li class="footer__address-item">地址：北京市海淀区学院路37号</li>
              <li class="footer__address-item">热线电话：400 123 45678</li>
              <li class="footer__address-item">联系邮箱： alangy@buaa.edu.cn</li>
            </ul>
            <ul class="footer__social-nav">
              <li class="footer__social-list">
                <a href="#" class="footer__social-link"><i class="fab fa-facebook-f"></i></a></li>
              <li class="footer__social-list"><a href="#" class="footer__social-link"><i class="fab fa-twitter"></i></a>
              </li>
              <li class="footer__social-list"><a href="#" class="footer__social-link"><i class="fab fa-youtube"></i></a>
              </li>
              <li class="footer__social-list">
                <a href="#" class="footer__social-link"><i class="fab fa-google-plus-g"></i></a></li>
              <li class="footer__social-list">
                <a href="#" class="footer__social-link"><i class="fab fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-12">
          <div class="footer__form">
            <h4 class="footer__nav-title footer__nav-title--dash footer__nav-title--dash-red">订阅最新消息！</h4>
            <p>在下方输入您的邮箱，即可获取我们的全部新品信息及促销信息</p>
            <form action="#" class="footer__form-box">
              <input type="email" placeholder="您的邮箱" required>
              <button class="btn btn--box btn--tiny btn--red btn--red-hover-red btn--uppercase font--bold " type="submit">订阅!</button>
            </form>
          </div>
        </div>
      </div>
    </div> <!-- End Footer Top Section -->
    <!-- Start Footer Bottom Section -->
    <div class="footer__bottom">
      <div class="row">
        <div class="col-lg-8 col-md-6 col-12">
          <!-- Start Footer Copyright Text -->
          <div class="footer__copyright-text">
            <p>Copyright &copy; <a href="mail://alangy@buaa.edu.cn">alangy</a>. 保留所有权利</p>
          </div> <!-- End Footer Copyright Text -->
        </div>
        <div class="col-lg-4 col-md-6 col-12">
          <!-- Start Footer Payment Logo -->
          <div class="footer__payment">
            <a href="#" class="footer__payment-link">
              <img src="/assets/img/company-logo/payment.png" alt="" class="footer__payment-img">
            </a>
          </div>  <!-- End Footer Payment Logo -->
        </div>
      </div>
    </div> <!-- End Footer Bottom Section -->
  </div>
</footer> <!-- ::::::  End  Footer ::::::  -->

<!-- jQuery JS -->
<script src="/assets/js/vendor/jquery-3.5.1.min.js"></script>
<!-- jQuery Migrate JS -->
<script src="/assets/js/vendor/jQuery-migrate-3.3.0.min.js"></script>
<!-- Modernizer JS -->
<script src="/assets/js/vendor/modernizr-2.8.3.min.js"></script>
<!-- Bootstrap JS -->
<script src="/assets/js/vendor/bootstrap.bundle.min.js"></script>
<!-- Slick Slider JS -->
<script src="/assets/js/plugins/slick.min.js"></script>
<!-- Countdown JS -->
<script src="/assets/js/plugins/jquery.countdown.min.js"></script>
<!-- Ajax JS -->
<script src="/assets/js/plugins/jquery.ajaxchimp.min.js"></script>
<!-- Jquery Nice Select JS -->
<script src="/assets/js/plugins/jquery.nice-select.min.js"></script>
<!-- Jquery Ui JS -->
<script src="/assets/js/plugins/jquery-ui.min.js"></script>
<!-- jquery magnific popup js -->
<script src="/assets/js/plugins/jquery.magnific-popup.min.js"></script>

<!-- Main JS -->
<script src="/assets/js/vendor/vendor.min.js"></script>
<script src="/assets/js/plugin/plugins.min.js"></script>

<!-- Main js file that contents all jQuery plugins activation. -->
<script src="/assets/js/main.js"></script>
<script>function reversefav(id) {

    $.post('/favorites/reverse',
        {
            product_id: id
        },
        function (data, status) {
            console.log(data);
            console.log(status);
            if (data.status == 1) {
                $("#fav" + id).attr('class', 'ion-android-favorite')
                $("#fav2" + id).attr('class', 'ion-android-favorite')
            } else if (data.status == 0) {
                $("#fav" + id).attr('class', 'ion-android-favorite-outline')
                $("#fav2" + id).attr('class', 'ion-android-favorite-outline')
            } else {
                alert("添加收藏失败，管理员不允许添加收藏，或者您还没有登录。请登录后再试");
            }
        })
}</script>

</body>
</html>

project/app/views/application/_footer_admin.html.erb
<!-- js -->
<script src="/vendors/scripts/core.js"></script>
<script src="/vendors/scripts/script2.min.js"></script>
<script src="/vendors/scripts/process.js"></script>
<script src="/vendors/scripts/layout-settings.js"></script>
<script src="/src/plugins/apexcharts/apexcharts.min.js"></script>
<script src="/src/plugins/datatables/js/jquery.dataTables.min.js"></script>
<script src="/src/plugins/datatables/js/dataTables.bootstrap4.min.js"></script>
<script src="/src/plugins/datatables/js/dataTables.responsive.min.js"></script>
<script src="/src/plugins/datatables/js/responsive.bootstrap4.min.js"></script>
<script src="/vendors/scripts/dashboard.js"></script>



<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

project/app/views/application/_header_admin.html.erb
<!-- Site favicon -->
<link rel="apple-touch-icon" sizes="180x180" href="/vendors/images/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/vendors/images/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/vendors/images/favicon-16x16.png">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="turbolinks-cache-control" content="no-cache">


<!-- Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<!-- CSS -->
<link rel="stylesheet" type="text/css" href="/vendors/styles/core.css">
<link rel="stylesheet" type="text/css" href="/vendors/styles/icon-font.min.css">
<link rel="stylesheet" type="text/css" href="/src/plugins/datatables/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="/src/plugins/datatables/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="/vendors/styles/style.css">



</head>
<body data-turbolinks='false'>
<!--
<div class="pre-loader">
  <div class="pre-loader-box">
    <div class="loader-logo"><img src="/vendors/images/deskapp-logo.svg" alt=""></div>
    <div class='loader-progress' id="progress_div">
      <div class='bar' id='bar1'></div>
    </div>
    <div class='percent' id='percent1'>0%</div>
    <div class="loading-text">
      Loading...
    </div>
  </div>
</div>
-->

<div class="header">
  <div class="header-left">
    <div class="menu-icon dw dw-menu"></div>
    <div class="search-toggle-icon dw dw-search2" data-toggle="header_search"></div>
    <div class="header-search">
      <form>
        <div class="form-group mb-0">
          <i class="dw dw-search2 search-icon"></i>
          <input type="text" class="form-control search-input" placeholder="Search Here">
          <div class="dropdown">
            <a class="dropdown-toggle no-arrow" href="#" role="button" data-toggle="dropdown">
              <i class="ion-arrow-down-c"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label">From</label>
                <div class="col-sm-12 col-md-10">
                  <input class="form-control form-control-sm form-control-line" type="text">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label">To</label>
                <div class="col-sm-12 col-md-10">
                  <input class="form-control form-control-sm form-control-line" type="text">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label">Subject</label>
                <div class="col-sm-12 col-md-10">
                  <input class="form-control form-control-sm form-control-line" type="text">
                </div>
              </div>
              <div class="text-right">
                <button class="btn btn-primary">Search</button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="header-right">
    <div class="dashboard-setting user-notification">
      <div class="dropdown">
        <a class="dropdown-toggle no-arrow" href="javascript:;" data-toggle="right-sidebar">
          <i class="dw dw-settings2"></i>
        </a>
      </div>
    </div>
    <div class="user-notification">
      <div class="dropdown">
        <a class="dropdown-toggle no-arrow" href="#" role="button" data-toggle="dropdown">
          <i class="icon-copy dw dw-notification"></i>
          <span class="badge notification-active"></span>
        </a>
      </div>
    </div>
    <div class="user-info-dropdown">
      <div class="dropdown">
        <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
						<span class="user-icon">
							<img src="/vendors/images/photo1.jpg" alt="">
						</span>
          <span class="user-name"><%= current_user.name %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
          <a class="dropdown-item" href="<%= edit_user_path current_user %>"><i class="dw dw-user1"></i>查看并编辑个人信息</a>
          <a class="dropdown-item" href="#"><i class="dw dw-help"></i>帮助</a>
          <%=link_to raw("<i class=\"dw dw-logout\"></i>注销登录"), destroy_user_session_path,  class: "dropdown-item" ,:method => :delete%>
        </div>
      </div>
    </div>
    <div class="github-link">
      <a href="" target="_blank"><img src="/vendors/images/github.svg" alt=""></a>
    </div>
  </div>
</div>

<div class="right-sidebar">
  <div class="sidebar-title">
    <h3 class="weight-600 font-16 text-blue">
      布局设置
      <span class="btn-block font-weight-400 font-12">页面显示设置</span>
    </h3>
    <div class="close-sidebar" data-toggle="right-sidebar-close">
      <i class="icon-copy ion-close-round"></i>
    </div>
  </div>
  <div class="right-sidebar-body customscroll">
    <div class="right-sidebar-body-content">
      <h4 class="weight-600 font-18 pb-10">上边栏背景风格</h4>
      <div class="sidebar-btn-group pb-30 mb-10">
        <a href="javascript:void(0);" class="btn btn-outline-primary header-white active">白色</a>
        <a href="javascript:void(0);" class="btn btn-outline-primary header-dark">黑色</a>
      </div>

      <h4 class="weight-600 font-18 pb-10">侧边栏背景风格</h4>
      <div class="sidebar-btn-group pb-30 mb-10">
        <a href="javascript:void(0);" class="btn btn-outline-primary sidebar-light ">白色</a>
        <a href="javascript:void(0);" class="btn btn-outline-primary sidebar-dark active">黑色</a>
      </div>

      <h4 class="weight-600 font-18 pb-10">菜单下拉样式</h4>
      <div class="sidebar-radio-group pb-10 mb-10">
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebaricon-1" name="menu-dropdown-icon" class="custom-control-input" value="icon-style-1" checked="">
          <label class="custom-control-label" for="sidebaricon-1"><i class="fa fa-angle-down"></i></label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebaricon-2" name="menu-dropdown-icon" class="custom-control-input" value="icon-style-2">
          <label class="custom-control-label" for="sidebaricon-2"><i class="ion-plus-round"></i></label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebaricon-3" name="menu-dropdown-icon" class="custom-control-input" value="icon-style-3">
          <label class="custom-control-label" for="sidebaricon-3"><i class="fa fa-angle-double-right"></i></label>
        </div>
      </div>

      <h4 class="weight-600 font-18 pb-10">菜单列表样式</h4>
      <div class="sidebar-radio-group pb-30 mb-10">
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebariconlist-1" name="menu-list-icon" class="custom-control-input" value="icon-list-style-1" checked="">
          <label class="custom-control-label" for="sidebariconlist-1"><i class="ion-minus-round"></i></label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebariconlist-2" name="menu-list-icon" class="custom-control-input" value="icon-list-style-2">
          <label class="custom-control-label" for="sidebariconlist-2"><i class="fa fa-circle-o" aria-hidden="true"></i></label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebariconlist-3" name="menu-list-icon" class="custom-control-input" value="icon-list-style-3">
          <label class="custom-control-label" for="sidebariconlist-3"><i class="dw dw-check"></i></label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebariconlist-4" name="menu-list-icon" class="custom-control-input" value="icon-list-style-4" checked="">
          <label class="custom-control-label" for="sidebariconlist-4"><i class="icon-copy dw dw-next-2"></i></label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebariconlist-5" name="menu-list-icon" class="custom-control-input" value="icon-list-style-5">
          <label class="custom-control-label" for="sidebariconlist-5"><i class="dw dw-fast-forward-1"></i></label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="sidebariconlist-6" name="menu-list-icon" class="custom-control-input" value="icon-list-style-6">
          <label class="custom-control-label" for="sidebariconlist-6"><i class="dw dw-next"></i></label>
        </div>
      </div>

      <div class="reset-options pt-30 text-center">
        <button class="btn btn-danger" id="reset-settings">重置设定</button>
      </div>
    </div>
  </div>
</div>

<div class="left-side-bar">
  <div class="brand-logo">
    <a href="<%= admin_path %>">
      <img src="/vendors/images/deskapp-logo.svg" alt="" class="dark-logo">
      <img src="/vendors/images/deskapp-logo-white.svg" alt="" class="light-logo">
    </a>
    <div class="close-sidebar" data-toggle="left-sidebar-close">
      <i class="ion-close-round"></i>
    </div>
  </div>
  <div class="menu-block customscroll">
    <div class="sidebar-menu">
      <ul id="accordion-menu">
        <li>
          <a href="<%= admin_path %>" class="dropdown-toggle no-arrow">
            <span class="micon dw dw-house-1"></span><span class="mtext">后台管理首页</span>
          </a>
        </li>
        <li>
          <a href="<%= transaction_orders_path %>" class="dropdown-toggle no-arrow">
            <span class="micon dw dw-invoice"></span><span class="mtext">订单管理</span>
          </a>
        </li>
        <li>
          <a href="<%= users_path %>" class="dropdown-toggle no-arrow">
            <span class="micon dw dw-calendar1"></span><span class="mtext">用户管理</span>
          </a>
        </li>
        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle">
            <span class="micon dw dw-edit-2"></span><span class="mtext">商品管理</span>
          </a>
          <ul class="submenu">
            <li><a href="<%= admin_path %>">所有商品</a></li>
            <li><a href="<%= new_product_path %>">新增商品</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle">
            <span class="micon dw dw-list3"></span><span class="mtext">商品类型</span>
          </a>
          <ul class="submenu">
            <li><a href="<%= product_types_path %>">所有类型</a></li>
            <li><a href="<%= new_product_type_path %>">新增类型</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle">
            <span class="micon dw dw-paint-brush"></span><span class="mtext">颜色管理</span>
          </a>
          <ul class="submenu">
            <li><a href="<%= colors_path %>">所有颜色</a></li>
            <li><a href="<%= new_color_path %>">新增颜色</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="mobile-menu-overlay"></div>