project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "devise_customed/registrations"}
  resources :users
  root 'products#index'
  resources :favorites
  resources :transaction_items
  resources :transaction_orders
  resources :cartitems
  resources :sizes
  get 'products/remove_picture', to: 'products#remove_picture'
  resources :products
  get 'all', to: "products#inspect", as: "inspect_all"
  resources :colors
  resources :product_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'admin', to: 'admin#show'
  get 'test', to: 'admin#test'
  get 'transaction_orders/:id/adminedit', to: 'transaction_orders#adminedit', as: "admin_edit_transaction_orders"
  get 'transaction_orders/:id/receive_product', to: 'transaction_orders#receive_product', as: "receive_product"
  match 'favorites/remove', to: 'favorites#destroy', as: "remove_product_favorites", via: :post
  match 'favorites/reverse', to: 'favorites#reverse', via: :post
  match 'users/:id/change_password', to: 'users#change_password', via: :post, as: "change_password"
  match 'api/getmoney',to:"transaction_orders#setpaid", via: :get, as:"receive_money"
end

project/app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

project/app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  include ApplicationHelper
  include CartitemsHelper
  before_action :set_cartitem, only: [:show, :edit, :update, :destroy]
  before_action :useriscustomer
  skip_before_action :verify_authenticity_token, only:[:create,:update]


  # GET /cartitems
  # GET /cartitems.json
  def index
    @cartitems = current_user.cartitems
  end

  # GET /cartitems/1
  # GET /cartitems/1.json
  def show
  end

  # GET /cartitems/new
  def new
    @cartitem = Cartitem.new
    @cartitem.user = current_user
  end

  # GET /cartitems/1/edit
  def edit
  end

  # POST /cartitems
  # POST /cartitems.json
  def create
    @cartitem = Cartitem.where user_id: current_user.id, product_id: params[:cartitem][:productid]
    @targetproduct = Product.find params[:cartitem][:productid]
    if @targetproduct.nil? || Integer(params[:cartitem][:quantity]) < 0
      redirect_to root_path
      return
    end
    if @cartitem.size==0
      @cartitem = Cartitem.new(cartitem_params)
      @cartitem.user = current_user
      @cartitem.product = Product.find params[:cartitem][:productid]
    else
      @cartitem=@cartitem[0]
      @cartitem.quantity = @cartitem.quantity+Integer(params[:cartitem][:quantity])
    end
    respond_to do |format|
      if @cartitem.save
        #format.html { redirect_to @targetproduct, notice: '成功添加到购物车' }
        format.json { render json:get_cart_info}
      else
        format.html { render @targetproduct }
        format.json { render json: @cartitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartitems/1
  # PATCH/PUT /cartitems/1.json
  def update
    respond_to do |format|
      if @cartitem.update(cartitem_params)
        format.html { redirect_to cartitems_url, notice: 'Cartitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartitem }
      else
        format.html { render :edit }
        format.json { render json: @cartitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartitems/1
  # DELETE /cartitems/1.json
  def destroy
    @cartitem.destroy
    respond_to do |format|
      format.html { redirect_to cartitems_url, notice: 'Cartitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cartitem
    @cartitem = Cartitem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cartitem_params
    params.require(:cartitem).permit(:quantity)
  end
end

project/app/helpers/cartitems_helper.rb
module CartitemsHelper
  def get_cart_info
    @result=Array.new
    @all=current_user.cartitems
    @all.each do |x|
      if x.product.pics.size!=0
        @result<<{
            name: x.product.name,
            quantity: x.quantity,
            product_id: x.product_id,
            total_price: x.quantity*x.product.price,
            price: x.product.price,
            image_directory:x.product.pics[0]
        }
      else
        @result<<{
            name: x.product.name,
            quantity: x.quantity,
            product_id: x.product_id,
            total_price: x.quantity*x.product.price,
            price: x.product.price,
        }
      end
    end
    @result
  end

end

project/app/views/cartitems/_form.html.erb
<%= form_with(model: cartitem, local: true) do |form| %>
  <% if cartitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cartitem.errors.count, "error") %> prohibited this cartitem from being saved:</h2>

      <ul>
        <% cartitem.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/cartitems/edit.html.erb
<h1>Editing Cartitem</h1>

<%= render 'form', cartitem: @cartitem %>

<%= link_to 'Show', @cartitem %> |
<%= link_to 'Back', cartitems_path %>

project/app/views/cartitems/index.html.erb
<%= render "header" %>
<!-- ::::::  Start  Breadcrumb Section  ::::::  -->
<div class="page-breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <ul class="page-breadcrumb__menu">
          <li class="page-breadcrumb__nav"><a href="#">首页</a></li>
          <li class="page-breadcrumb__nav active">购物车</li>
        </ul>
      </div>
    </div>
  </div>
</div> <!-- ::::::  End  Breadcrumb Section  ::::::  -->

<!-- ::::::  Start  Main Container Section  ::::::  -->
<main id="main-container" class="main-container">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-content">
          <h5 class="section-content__title">当前购物车中的商品</h5>
        </div>
        <% if current_user.cartitems.size == 0 %>
          <p class="m-5">购物车为空，再去逛逛吧</p>
        <% else %>
          <div class="table-content table-responsive cart-table-content m-t-30">
            <table>
              <thead>
              <tr>
                <th>图片</th>
                <th>商品名</th>
                <th>单个价格</th>
                <th>数量</th>
                <th>总价</th>
                <th>删除</th>

              </tr>
              </thead>
              <tbody>


              <% @cartitems.each do |item| %>
                <p hidden="true"><%= item.id %></p>
                <tr>
                  <td class="product-thumbnail">
                    <a href="#"><img class="img-fluid" src="<%= item.product.pics[0].url %>" alt=""></a>
                  </td>
                  <td class="product-name">
                    <%= link_to item.product.name, item.product %></td>
                  <td class="product-price-cart"><span class="amount">¥<%= item.product.price %></span></td>
                  <td class="product-quantity">
                    <div class="quantity d-inline-block">
                      <input class='cartitem_change_quantity' id='<%= item.id %>' type="number" min="1" step="1" value="<%= item.quantity %>">
                    </div>
                  </td>
                  <td class="product-subtotal">¥<%= item.quantity * item.product.price %></td>
                  <td class="product-add-cart"><%= link_to " ✕ ", cartitem_path(item), method: :delete, class: 'btn btn--box btn--tiny btn--radius btn--red btn--red-hover-black  font--semi-bold fa-pull-right m-3' %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>  <!-- End Wishlist Table -->
          <%= link_to '确认无误，去结账', new_transaction_order_path, class: 'btn btn--box btn--tiny btn--radius btn--red btn--red-hover-black btn--uppercase font--semi-bold fa-pull-right m-3' %>
        <% end %>
        <!-- Start Wishlist Table -->
      </div>
    </div>
  </div>
</main> <!-- ::::::  End  Main Container Section  ::::::  -->


<!-- material-scrolltop button -->
<button class="material-scrolltop" type="button"></button>

<!-- Start Modal Add cart -->
<div class="modal fade" id="modalAddCart" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog  modal-dialog-centered modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Product Successfully Added To Your Shopping Cart</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-6">
                  <div class="modal__product-img">
                    <img class="img-fluid" src="assets/img/product/size-normal/product-home-1-img-1.jpg" alt="">
                  </div>
                </div>
                <div class="col-md-6">
                  <span class="modal__product-title">SonicFuel Wireless Over-Ear Headphones</span>
                  <span class="modal__product-price m-tb-15">$31.59</span>
                  <ul class="modal__product-info ">
                    <li>Size:<span> S</span></li>
                    <li>Quantity:<span>3</span></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-md-6 modal__border">
              <span class="modal__product-cart-item">There are 3 items in your cart.</span>
              <ul class="modal__product-shipping-info m-tb-15">
                <li>Total products:<span>$94.78</span></li>
                <li>Total shipping:<span>$7.00</span></li>
                <li>Taxes:<span>$0.00</span></li>
                <li>Total: <span>$101.78 (tax excl.)</span></li>
              </ul>

              <div class="modal__product-cart-buttons">
                <a href="#" class="btn btn--box btn--radius btn--small btn--black btn--black-hover-red btn--uppercase btn--weight" data-dismiss="modal">Continue
                  Shopping</a>
                <a href="checkout.html" class="btn btn--box btn--radius btn--small btn--black btn--black-hover-red btn--uppercase btn--weight">Checkout</a>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- End Modal Add cart -->

<!-- Start Modal Quickview cart -->
<div class="modal fade" id="modalQuickView" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog  modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Quick View</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"> <i class="fal fa-times"></i></span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6">
              <div class="product-gallery-box m-b-60">
                <div class="modal-product-image--large">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-large/product-gallery-large-1.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-large/product-gallery-large-2.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-large/product-gallery-large-3.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-large/product-gallery-large-4.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-large/product-gallery-large-5.jpg" alt="">
                </div>
                <div class="modal-product-image--thumb pos-relative">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-thumb/product-gallery-thumb-1.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-thumb/product-gallery-thumb-2.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-thumb/product-gallery-thumb-3.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-thumb/product-gallery-thumb-4.jpg" alt="">
                  <img class="img-fluid" src="assets/img/product/gallery/gallery-thumb/product-gallery-thumb-5.jpg" alt="">
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="product-details-box">
                <h5 class="title title--normal m-b-20">Aliquam lobortis</h5>
                <div class="product__price">
                  <span class="product__price-del">$35.90</span>
                  <span class="product__price-reg">$31.69</span>
                </div>
                <div class="product__stock m-tb-20">
                  <span class="product__stock--in"><i class="fas fa-check-circle"></i> 199 IN STOCK</span>
                </div>
                <div class="product-var p-t-30">
                  <div class="product-color product-var__item">
                    <span class="product-var__text">Color</span>
                    <div class="sidebar__color-filter ">
                      <label class="product-color"><input name="product-color" type="radio" class="product-color-select" value="color-red"><span></span></label>
                      <label class="product-color"><input name="product-color" type="radio" class="product-color-select" value="color-green" checked><span></span></label>
                      <label class="product-color"><input name="product-color" type="radio" class="product-color-select" value="color-blue"><span></span></label>
                    </div>
                  </div>
                  <div class="product-quantity product-var__item">
                    <span class="product-var__text">Quantity</span>
                    <div class="product-quantity-box">
                      <div class="quantity">
                        <input type="number" min="1" max="9" step="1" value="1">
                      </div>
                      <a href="#modalAddCart" data-toggle="modal" data-dismiss="modal" class="btn btn--box btn--radius btn--small btn--black btn--black-hover-red btn--uppercase btn--weight m-l-20">+
                        Add to cart</a>
                    </div>
                  </div>
                </div>

                <div class="product__desc m-t-25 m-b-30">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco,Proin
                    lectus ipsum, gravida et mattis vulputate, tristique ut lectus</p>
                </div>

                <div class="product-links">
                  <div class="product-social m-tb-30">
                    <span>SHARE THIS PRODUCT</span>
                    <ul class="product-social-link">
                      <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                      <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                      <li><a href="#"><i class="fab fa-pinterest"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- End Modal Quickview cart -->
<%= render "footer" %>

project/app/views/cartitems/new.html.erb
<h1>New Cartitem</h1>

<%= render 'form', cartitem: @cartitem %>

<%= link_to 'Back', cartitems_path %>

project/app/views/cartitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @cartitem.quantity %>
</p>

<%= link_to 'Edit', edit_cartitem_path(@cartitem) %> |
<%= link_to 'Back', cartitems_path %>